### PR TITLE
Add support for CMake 2.8.12

### PR DESCRIPTION
**Pull request by scunz**

### CODE REVIEW

**Comment by scunz** [comment]
@antis81, here we go: Support for CMake 2.8.12... Does this look okay to you?

**Comment by antis81** [comment]
Almost Ok. This warning is left:

```
CMake Warning (dev) at MacGitverMain/Main/CMakeLists.txt:38 (TARGET_LINK_LIBRARIES):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "MacGitver".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * cmake/Qt4.cmake:121 (TARGET_LINK_LIBRARIES)

This warning is for project developers.  Use -Wno-dev to suppress it.
```

Nothing too serious :smile: .

**Comment by antis81** [comment]
Sorry my fault - checked on the wrong branch. Everything looks good :+1:. Feel free to merge :boat:.

**Comment by scunz** [comment]
Yeah, these warnings are nasty. CMP0023 is silly in my book; as well as changing the syntax from `LINK_PRIVATE` (since 2.8.7) to additionally support `PRIVATE` (since 2.8.12).

**Comment by scunz** [comment]
Okay, merged these branches; though did not test on Windows.

**Pull request merged**
