### PR TITLE
New Feature: Index view

### PR DESCRIPTION
**Pull request by antis81**
This PR is meant to be merged after the submodules libGitWrap and libMacGitverModules support the stage/index view.

### CODE REVIEW

**Comment by scunz** [comment]
I don't want to mess up your workflow, but these integrations are done automatically on a 6 hour rhythm for any change that is present on the dev-branch.
To my personal experience it's most easy to `cd libMacGitverModules && git checkout topic/foo` and ignore all changes to the super project.

**Comment by antis81** [comment]
Thanks again for clarifying. I didn't like my workflow either, as I have to repeat every step several times (e.g. the branching). So this is much easier.

**Comment by scunz** [comment]
For myself, I already concluded several times, that _any_ workflow based on git submodules is very likely to bring in lots of disadvantages. And I wouldn't recommend it for anybody unless there are clear, big individual modules to be separated. However, at the same point, it's undeniable to mention that there is nothing better available, neither in git nor in any dvcs found elsewhere.

**Comment by antis81** [comment]
Fully agreed :+1:. For the upcoming Git 1.8.2, there's a comment in the changelog:

> - "git submodule" started learning a new mode to integrate with the
>   tip of the remote branch (as opposed to integrating with the commit
>   recorded in the superproject's gitlink).

I'm excited to see it in real life :smile:.

**Comment by scunz** [comment]
I actually commented a few times on that change on the git mailinglist. But there was never any reply on my comments, so I finally lost track of (and interest in) it.

**Pull request closed without merging**
